name: Build Release APK
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decode secret files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > encoded_google_services_json.txt
          touch app/google-services.json
          openssl base64 -d -out app/google-services.json < encoded_google_services_json.txt
          echo "${{ secrets.KEYSTORE }}" > encoded_keystore.txt
          touch app/roketto.keystore
          openssl base64 -d -out app/roketto.keystore < encoded_keystore.txt
      - name: Setting constants
        env:
          DEFAULT_WEB_CLIENT_ID: ${{ secrets.DEFAULT_WEB_CLIENT_ID }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          perl -pi -e 's/FIREBASE_ID/$ENV{DEFAULT_WEB_CLIENT_ID}/' app/src/main/java/it/rokettoapp/roketto/util/Constants.java
          perl -pi -e 's/FIREBASE_URL/$ENV{FIREBASE_DATABASE_URL}/' app/src/main/java/it/rokettoapp/roketto/util/Constants.java
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build
        id: build
        run: ./gradlew assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/signed/release
